### ISSUE TITLE
Broken on python 3.12 due to distutil removal

### ISSUE THREAD

**Issue by jfrost-mo** [conda-incubator/ensureconda#24]
On Python 3.12.0 ensureconda fails to run (at least from inside conda lock) due to distutils being removed.
```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/conda-lock", line 5, in <module>
    from conda_lock import main
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/conda_lock/__init__.py", line 3, in <module>
    from conda_lock.conda_lock import main
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 38, in <module>
    from ensureconda.api import ensureconda
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/ensureconda/__init__.py", line 2, in <module>
    from .api import ensureconda
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/ensureconda/api.py", line 2, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

distutils.version should be replaced by something else. The [recommended](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html) replacement is [packaging.version.Version](https://packaging.pypa.io/en/latest/version.html).

#22 contains a fix to do this conversion.

**Comment by swertz** [comment]
Sorry for pinging again, but any chance this could be merged? `conda-lock` is still broken because of it...

**Comment by maresb** [comment]
Ok, I got #22 merged, and also got maintainer permissions here. The GHA runners for the tests post-merge seem to be still enqueue. I'd like to cut a patch release as soon as the CI turns green. Please ping me in case they're green but you don't see a release.

**Comment by jfrost-mo** [comment]
Thank you :) I see [the release](https://github.com/conda-incubator/ensureconda/releases/tag/v1.4.4) published now. I'll go and open a PR against conda-lock to update the dependencies there.
